### ISSUE TITLE
Create missing credential files if not present

### ISSUE THREAD

**Issue by tpraxl** [friesenkiwi/ansible-collection-uberspace#3]
Primer: I think your collection is actually very well done. I enjoyed studying it and playing with it so far.

This issue refers to PR #2 

The guide contained wrong locations of files that are expected, PR #2 will fix that.

However, I think, missing files that can be automatically populated, such as loginpassword and session, should be created.

This leaves only the `inwx/{{inwx_user}}-pw` file to be mandatory, but this is only required for users that actually want to use the relevant INWX roles.

What do you think? Should we create those missing files on demand?

**Comment by friesenkiwi** [comment]
Actually, those missing files should automatically be created if missing and possible:

* `uberspace_newloginpassword` is generated/written/populated by `lookup('password', …)` in https://github.com/friesenkiwi/ansible-collection-uberspace/blob/master/roles/uberspace_account/defaults/main.yml#L7 (for `lookup('password')` see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_lookup.html#synopsis)
* `uberspace_loginpassword` can not be written, if the account wasn't created by the role (in which case it's created and populated by the aforementioned  `uberspace_newloginpassword`)
* `uberspace_sessionfile` is written in https://github.com/friesenkiwi/ansible-collection-uberspace/blob/master/roles/uberspace_account/tasks/login.yml#L30 and https://github.com/friesenkiwi/ansible-collection-uberspace/blob/master/roles/uberspace_account/tasks/register.yml#L46

Or did I misunderstand something?

**Comment by tpraxl** [comment]
Well, they have not been created when they were missing during my test runs. I needed to follow the error messages and looked up the code to create them manually.

> Or did I misunderstand something?

Thanks for the links. I am running out of time today, but I will look that up and try to reproduce it later.

**Comment by tpraxl** [comment]
The files are created. Not sure why that did not happen in the first place, but I removed folders at different levels, up to the root credentials folder and it works. Perfect. Closing this.
